app/routes.py
import math
import os
import sqlite3
from datetime import datetime
from pathlib import Path

import pandas as pd
from flask import Blueprint, current_app, render_template, request

bp = Blueprint('main', __name__)

# Define a global variable to store the df loaded from the database
global_df = None
global_df_filtered = None
current_test_runs = []


def get_most_recent_run_name(folder_path):
    # Get the most recent test_run database name
    test_runs = [f for f in os.listdir(folder_path) if
                 os.path.isfile(os.path.join(folder_path, f))]
    return max(test_runs, key=extract_datetime_from_filename)


def extract_datetime_from_filename(file_name):
    # function to extract the datetime of the test execution from the database filename
    file_name = file_name.replace("metamorphic_test_run_", "").replace(".db", "")
    return datetime.strptime(file_name, "%Y-%m-%d_%H-%M-%S")


def get_df_from_db(selected_test_runs):
    folder_path = current_app.config['DIR']

    if not selected_test_runs:
        selected_test_runs = [get_most_recent_run_name(folder_path)]

    global current_test_runs
    current_test_runs = selected_test_runs

    # create a dataframe from all selected test runs
    df_list = []
    for test_run in selected_test_runs:
        db_path = os.path.join(os.getcwd(), folder_path, test_run)
        conn = sqlite3.connect(db_path)
        df_test_run = get_test_results_df(conn)
        df_list.append(df_test_run)
        conn.close()

    # update global df variable
    global global_df
    global_df = pd.concat(df_list)
    return global_df


def get_test_results_df(conn):
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM mtc_results")
    rows = cursor.fetchall()
    df = pd.DataFrame(rows, columns=[desc[0] for desc in cursor.description])
    df['relation_result'] = df['relation_result'].map({'True': True, 'False': False})
    return df


def compile_metadata(df):
    total = df.shape[0]
    passed = df[df["test_result"] == "passed"].shape[0]
    failed = df[df["test_result"] == "failed"].shape[0]
    skipped = df[df["test_result"] == "skipped"].shape[0]
    duration = round(df["duration"].sum(), 2)
    return total, passed, failed, skipped, duration


def process_df(df):
    # do not consider skipped test cases in the calculation of the failure rate
    df = df.loc[df['test_result'] != 'skipped']

    # Group the DataFrame by "mr_name" and "sut_name" and count the occurrences of
    # "True" in "relation_result"
    grouped = df.groupby(["mr_name", "sut_name"], group_keys=True)["test_result"].apply(
        lambda x: (x == "failed").sum())

    # Calculate the total count for each group
    total_count = df.groupby(["mr_name", "sut_name"], group_keys=True).size()

    # Calculate the failure rate per group
    failure_rate = grouped / total_count

    # Convert the failure rate Series to a DataFrame with proper column names
    df_fr = failure_rate.unstack()

    # add average row
    df_fr.loc['average'] = df_fr.mean()

    # beauty updates
    df_fr.columns = [col.replace('test_', '') for col in df_fr.columns]
    df_fr.columns = [col.replace('_', ' ') for col in df_fr.columns]
    df_fr.index = [idx.replace('_', ' ') for idx in df_fr.index]
    df_fr = (df_fr * 100).round(2).astype(str) + '%'
    df_fr = df_fr.replace('nan%', '-')

    styler = df_fr.style

    print(styler.to_latex(hrules=True))

    return df_fr


def paginate_df(df):
    page = request.args.get('page', 1, type=int)
    per_page = 20

    # Calculate the start and end indices for the current page
    start_idx = (page - 1) * per_page
    end_idx = start_idx + per_page

    # Slice the DataFrame based on the indices
    sliced_df = df[start_idx:end_idx][["_id", "mtc_name", "mr_name", "sut_name",
                                       "parameters", "test_result"]]

    # Calculate the total number of pages for the pagination links
    total_pages = int(math.ceil(len(df) / per_page))
    return page, total_pages, sliced_df


def get_sorted_files(folder_path):
    files = [f for f in os.listdir(folder_path) if
             os.path.isfile(os.path.join(folder_path, f))]

    return sorted(files, key=extract_datetime_from_filename, reverse=True)


@bp.route('/')
def landing_page():
    # Get the list of all db files
    folder_path = current_app.config['DIR']

    # check if test_results is empty: No tests have been executed with --html-report
    if not os.path.exists(folder_path) or not os.listdir(folder_path):
        # if no results have been found, display the following hint message
        hint_message = ('Please run a test using <span style="color: blue; font-weight: bold'
                        ';">poetry run pytest --html-report &lt;test-file path&gt;</span>.')
        return render_template("empty_landing_page.html", hint_message=hint_message)

    files = get_sorted_files(folder_path)

    if global_df is None:
        df = get_df_from_db(selected_test_runs=current_test_runs)
    else:
        df = global_df

    df_fr = process_df(df)
    total, passed, failed, skipped, duration = compile_metadata(df)

    landing_page_data = {
        'num_executed': total,
        'num_passed': passed,
        'num_failed': failed,
        'num_skipped': skipped,
        'execution_time': duration,
        'table_data': df_fr
    }

    if global_df_filtered is not None:
        df_filtered = global_df_filtered
    else:
        df_filtered = df

    # Sort the DataFrame by the "relation_result" column
    df_filtered = df_filtered.sort_values(by='relation_result', ascending=True)

    # paginate the df
    page, total_pages, df_sliced = paginate_df(df_filtered)

    return render_template(
        template_name_or_list='landing_page.html',
        files=files,
        current_test_run=current_test_runs,
        data=landing_page_data,
        individual_test_results=df_sliced,
        total_pages=total_pages,
        current_page=page,
        unique_mr_names=df["mr_name"].unique(),
        unique_sut_names=df["sut_name"].unique(),
        unique_test_results=df["test_result"].unique()
    )


@bp.route('/select', methods=['GET'])
def select_test_run():
    # Reset filtered df when a new test run is selected, there should be no filters applied.
    global global_df_filtered
    global_df_filtered = None

    # Get the list of all db files
    folder_path = current_app.config['DIR']

    files = get_sorted_files(folder_path)

    # connect to selected test run databases and fetch stored results
    selected_test_runs = request.args.getlist('test_run')
    df = get_df_from_db(selected_test_runs=selected_test_runs)

    df_fr = process_df(df)
    total, passed, failed, skipped, duration = compile_metadata(df)

    landing_page_data = {
        'num_executed': total,
        'num_passed': passed,
        'num_failed': failed,
        'num_skipped': skipped,
        'execution_time': duration,
        'table_data': df_fr
    }

    # Sort the DataFrame by the "relation_result" column
    df = df.sort_values(by='relation_result', ascending=True)

    # paginate the df
    page, total_pages, df_sliced = paginate_df(df)

    return render_template(
        'landing_page.html',
        individual_test_results=df_sliced,
        current_test_run=current_test_runs,
        files=files,
        data=landing_page_data,
        total_pages=total_pages,
        current_page=page,
        unique_mr_names=df['mr_name'].unique(),
        unique_sut_names=df["sut_name"].unique(),
        unique_test_results=df["test_result"].unique()
    )


@bp.route('/filter', methods=['GET'])
def filter_test_cases():  # pylint: disable=too-many-locals
    # Get the list of all db files
    folder_path = current_app.config['DIR']

    files = get_sorted_files(folder_path)

    if global_df is None:
        raise TypeError("No test run selected as global_df is None")

    df = global_df

    # Retain original unfiltered options for dropdowns
    all_mr_names = df['mr_name'].unique()
    all_sut_names = df['sut_name'].unique()
    all_test_results = df['test_result'].unique()

    df_fr = process_df(df)
    total, passed, failed, skipped, duration = compile_metadata(df)

    landing_page_data = {
        'num_executed': total,
        'num_passed': passed,
        'num_failed': failed,
        'num_skipped': skipped,
        'execution_time': duration,
        'table_data': df_fr
    }

    selected_mr = request.args.getlist('mr_name')
    selected_sut = request.args.getlist('sut_name')
    selected_test_result = request.args.getlist('test_result')
    substring = request.args.get('substring')

    # Filter by Metamorphic Relation
    if selected_mr and selected_mr != ["all"]:
        df = df[df['mr_name'].isin(selected_mr)]

    # Filter by System Under Test
    if selected_sut and selected_sut != ["all"]:
        df = df[df['sut_name'].isin(selected_sut)]

    # Filter by Test Result
    if selected_test_result and selected_test_result != ["all"]:
        df = df[df['test_result'].isin(selected_test_result)]

    # Apply substring filter
    if substring:
        df = df[df.applymap(lambda cell: substring.lower() in str(cell).lower()).any(axis=1)]

    # Sort the DataFrame by the "relation_result" column
    df = df.sort_values(by='relation_result', ascending=True)

    # update the global df variable
    global global_df_filtered
    global_df_filtered = df

    # Paginate the df
    page, total_pages, df_sliced = paginate_df(df)

    return render_template(
        'landing_page.html',
        files=files,
        individual_test_results=df_sliced,
        current_test_run=current_test_runs,
        data=landing_page_data,
        total_pages=total_pages,
        current_page=page,
        unique_mr_names=all_mr_names,
        unique_sut_names=all_sut_names,
        unique_test_results=all_test_results
    )


def _get_values_valid_path(row, value_type):
    separator = "__\n\r__"
    values = row[value_type].split(separator)

app/templates/empty_landing_page.html
<!DOCTYPE html>
<html>
<head>
    <title>GeMTest: General Metamorphic Testing Framework</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <style>
        th {
            background-color: lightgray;
        }
    </style>
</head>
<body>
<h1>GeMTest: General Metamorphic Testing Framework</h1>
<form method="GET" action="{{ url_for('main.select_test_run') }}" class="select-form">
    <label for="test_run">Filter by Metamorphic Test Run:</label>
    <br>
    <select id="test_run" name="test_run" multiple class="wide-select" style="margin-left: 10px;">
        <option value="" disabled selected>No test result available</option>
    </select>
    <p>{{ hint_message | safe }}</p>
</form>
</body>
</html>

app/templates/landing_page.html
<!DOCTYPE html>
<html>
<head>
    <title>GeMTest: General Metamorphic Testing Framework</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <style>
        th {
            background-color: lightgray;
        }
    </style>
</head>
<body>
<h1>GeMTest: General Metamorphic Testing Framework</h1>
<form method="GET" action="{{ url_for('main.select_test_run') }}" class="select-form">
    <label for="test_run">Filter by Metamorphic Test Run:</label>
    <br>
    <select id="test_run" name="test_run" multiple multiple style="margin-left: 10px;">
        {% for test_run in files %}
            <option value="{{ test_run }}"
                    {% if current_test_run == test_run %}selected{% endif %}>{{ test_run }}</option>
        {% endfor %}
    </select>
    <div class="filter-button">
        <button type="submit">Apply Selection</button>
    </div>
</form>

<div class="data-box">
    <p>Number of executed test cases: {{ data['num_executed'] }}</p>
    <p>Number of passed test cases: {{ data['num_passed'] }}</p>
    <p>Number of failed test cases: {{ data['num_failed'] }}</p>
    <p>Number of skipped test cases: {{ data['num_skipped'] }}</p>
    <p>Execution time: {{ data['execution_time'] }} seconds</p>
</div>
<h2>Failure rate Overview</h2>
<table>
    <tr>
        <th></th>
        {% for col_name in data['table_data'].columns %}
            <th>{{ col_name }}</th>
        {% endfor %}
    </tr>
    {% for index, row in data['table_data'].iterrows() %}
        <tr>
            <th class="header">{{ index }}</th>
            {% for value in row %}
                <td>{{ value }}</td>
            {% endfor %}
        </tr>
    {% endfor %}
</table>
<h2>Individual Metamorphic Test Cases</h2>

<form method="GET" action="{{ url_for('main.filter_test_cases') }}" class="filter-form">
    <div class="filter-row">
        <div class="filter-item">
            <label for="mr_name">Filter by Metamorphic Relation:</label>
            <select id="mr_name" name="mr_name" multiple>
                <option value="all" {% if 'all' in request.args.getlist('mr_name') %} selected {% endif %}>All</option>
                {% for mr_name in unique_mr_names %}
                    <option value="{{ mr_name }}" {% if mr_name in request.args.getlist('mr_name') %} selected {% endif %}>
                        {{ mr_name }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="filter-item">
            <label for="sut_name">Filter by System under Test:</label>
            <select id="sut_name" name="sut_name" multiple>
                <option value="all" {% if 'all' in request.args.getlist('sut_name') %} selected {% endif %}>All</option>
                {% for sut_name in unique_sut_names %}
                    <option value="{{ sut_name }}" {% if sut_name in request.args.getlist('sut_name') %} selected {% endif %}>
                        {{ sut_name }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="filter-item">
            <label for="test_result">Filter by Outcome:</label>
            <select id="test_result" name="test_result" multiple>
                <option value="all" {% if 'all' in request.args.getlist('test_result') %} selected {% endif %}>All</option>
                {% for test_result in unique_test_results %}
                    <option value="{{ test_result }}" {% if test_result in request.args.getlist('test_result') %} selected {% endif %}>
                        {{ test_result }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div class="filter-item">
            <label for="substring">Filter by Substring:</label>
            <input type="text" id="substring" name="substring" value="{{ request.args.get('substring', '') }}">
        </div>
    </div>
    <div class="filter-button">
        <button type="submit">Apply Filter</button>
    </div>
</form>


<table>
    <tr>
        <th>MTC name</th>
        <th>Outcome</th>
        <th>MR name</th>
        <th>SUT name</th>
        <th>Parameters</th>

    </tr>
    {% for index, row in individual_test_results.iterrows() %}
        <tr>
            <td><a href="{{ url_for('main.mtc_detail_view', test_case_id=row['_id']) }}"
                   target="_blank">{{ row['mtc_name'] }}</a></td>
            <td class="{% if row['test_result'] == 'failed' %}failed{% elif row['test_result'] == 'passed' %}passed{% elif row['test_result'] == 'skipped' %}skipped{% endif %}">{{ row['test_result'] }}</td>
            <td>{{ row['mr_name'] }}</td>
            <td>{{ row['sut_name'] }}</td>
            <td>{{ row['parameters'] }}</td>
        </tr>
    {% endfor %}
</table>
<div class="pagination-container">
    <div class="pagination">
        {% if current_page != 1 %}
            <a href="{{ url_for('main.filter_test_cases', page=1, mr_name=request.args.getlist('mr_name'), sut_name=request.args.getlist('sut_name'), test_result=request.args.getlist('test_result'), substring=request.args.get('substring')) }}">First</a>
            <a href="{{ url_for('main.filter_test_cases', page=current_page-1, mr_name=request.args.getlist('mr_name'), sut_name=request.args.getlist('sut_name'), test_result=request.args.getlist('test_result'), substring=request.args.get('substring')) }}">Previous</a>
        {% endif %}

        {% for num in range(1, total_pages + 1) %}
            {% if num == current_page %}
                <a class="active" href="{{ url_for('main.filter_test_cases', page=num, mr_name=request.args.getlist('mr_name'), sut_name=request.args.getlist('sut_name'), test_result=request.args.getlist('test_result'), substring=request.args.get('substring')) }}">{{ num }}</a>
            {% else %}
                <a href="{{ url_for('main.filter_test_cases', page=num, mr_name=request.args.getlist('mr_name'), sut_name=request.args.getlist('sut_name'), test_result=request.args.getlist('test_result'), substring=request.args.get('substring')) }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if current_page != total_pages %}
            <a href="{{ url_for('main.filter_test_cases', page=current_page+1, mr_name=request.args.getlist('mr_name'), sut_name=request.args.getlist('sut_name'), test_result=request.args.getlist('test_result'), substring=request.args.get('substring')) }}">Next</a>
            <a href="{{ url_for('main.filter_test_cases', page=total_pages, mr_name=request.args.getlist('mr_name'), sut_name=request.args.getlist('sut_name'), test_result=request.args.getlist('test_result'), substring=request.args.get('substring')) }}">Last</a>
        {% endif %}
    </div>
</div>
</body>
</html>

app/templates/mtc_detail_view.html
<!DOCTYPE html>
<html>
<head>
    <title>MTC Detail View</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
</head>
<body>
<h1>MTC Detail View</h1>
<p>Test Case ID: {{ test_case_id }}</p>
<p>System Under Test: {{ sut_name }}</p>
<p>Metamorphic Relation: {{ mr_name }}</p>
<p>Metamorphic Test Case: {{ mtc_name }}</p>
<p>Test Result: <span style="color:
        {% if test_result == 'failed' %}red{% elif test_result == 'passed' %}green{% elif test_result == 'skipped' %}{{ skipped_color }}{% endif %}">{{ test_result }}
  </span></p>

<div class="container">
    <table>
        <tr>
            <th>Input</th>
            <th>SUT</th>
            <th>Output</th>
        </tr>
        {% for i in range(source_inputs['values']|length) %}
            <tr>
                {% if source_inputs['is_valid_path'][i] %}
                    <td class="input-cell"><img src="{{ url_for('static', filename=source_inputs['values'][i]) }}"
                                                width="100" height="100" alt=""></td>
                {% else %}
                    <td class="input-cell">{{ source_inputs['values'][i] }}</td>
                {% endif %}

                <td><span class="inline"><span>{{ sut }}</span></span></td>

                {% if source_outputs['is_valid_path'][i] %}
                    <td class="input-cell"><img src="{{ url_for('static', filename=source_outputs['values'][i]) }}"
                                                width="100" height="100" alt=""></td>
                {% else %}
                    <td class="input-cell">{{ source_outputs['values'][i] }}</td>
                {% endif %}
            </tr>
        {% endfor %}

        <tr>
            <td>{{ transformation }}</td>
            <td></td>
            <td>
                {% set relation_parts = relation.split(':') %}
                {{ relation_parts[0] }}:
                {% set result_with_arrows = relation_parts[1].strip() %}
                {% set result = result_with_arrows.split()[0] %}
                {% if result == 'passed' %}
                    <span class="inline" style="color: green">{{ result }}</span>
                    {{ result_with_arrows|replace(result, '') }}
                {% elif result == 'failed' %}
                    <span class="inline" style="color: red">{{ result }}</span>
                    {{ result_with_arrows|replace(result, '') }}
                {% elif result == 'skipped' %}
                    <span class="inline" style="color: {{ skipped_color }}">{{ result }}</span>
                    {{ result_with_arrows|replace(result, '') }}
                {% else %}
                    {{ result_with_arrows }}
                {% endif %}
            </td>
        </tr>

        {% for i in range(followup_inputs['values']|length) %}
            <tr>
                {% if followup_inputs['is_valid_path'][i] %}
                    <td class="input-cell"><img src="{{ url_for('static', filename=followup_inputs['values'][i]) }}"
                                                width="100" height="100" alt=""></td>
                {% else %}
                    <td class="input-cell">{{ followup_inputs['values'][i] }}</td>
                {% endif %}

                <td>{{ sut }}</td>

                {% if followup_outputs['is_valid_path'][i] %}
                    <td class="input-cell"><img src="{{ url_for('static', filename=followup_outputs['values'][i]) }}"
                                                width="100" height="100" alt=""></td>
                {% else %}
                    <td class="input-cell">{{ followup_outputs['values'][i] }}</td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
</div>

<p>Standard Output: {{ stdout }}</p>
<p>Standard Error: {{ stderr }}</p>
</body>
</html>